namespace Aigamo.ResXGenerator.Tools;

internal static class Constants
{
	public const string Version = "4.4.1";
	public const string SystemGlobalization = $"{nameof(System)}.{nameof(System.Globalization)}";
	public const string SystemResources = $"{nameof(System)}.{nameof(System.Resources)}";
	public const string SystemCodeDomCompiler = $"{nameof(System)}.{nameof(System.CodeDom)}.{nameof(System.CodeDom.Compiler)}";
	public const string AutoGeneratedHeader =
		"""
		// ------------------------------------------------------------------------------
		//	<auto-generated>
		//		This code was generated by Aigamo.ResXGenerator.
		//
		//		Changes to this file may cause incorrect behavior and will be lost if
		//		the code is regenerated.
		//	</auto-generated>
		// ------------------------------------------------------------------------------
		""";
	public const string GeneratedCodeAttribute = $"""[GeneratedCode("Aigamo.ResXGenerator", "{Version}")]""";
	public const string SResourceManagerVariable = "s_resourceManager";
	public const string ResourceManagerVariable = "ResourceManager";
	public const string CultureInfoVariable = "CultureInfo";
	public const string NewLine = "\n";
}
